### ISSUE TITLE
helm_resource fails during the installation of helm charts to custom namespaces

### ISSUE THREAD

**Issue by mars-f** [tilt-dev/tilt-extensions#419]
The `helm_resource` extension fails during the installation of helm charts to custom namespaces.

See also #374 

**Steps to reproduce**

The following Tiltfile reproduces the bug:

```python
load('ext://helm_resource', 'helm_resource', 'helm_repo')

helm_repo(
    'traefik-upstream',
    'https://helm.traefik.io/traefik',
)

helm_resource(
    'traefik',
    'traefik-upstream/traefik',
    namespace='traefik',
    flags=[
        '--create-namespace',
    ],
    resource_deps=['traefik-upstream'],
)
```

**Expected behaviour**

`tilt up` should complete without error.  There should be a `traefik` pod in the `traefik` namespace.

**Actual result**

`tilt up` throws an error:

```
❯ tilt up --stream
Tilt started on http://localhost:10350/
v0.30.3, built 2022-06-10

Initial Build
Loading Tiltfile at: /Users/.../src/helm_resource-bugfix/Tiltfile
Successfully loaded Tiltfile (833.760038ms)
traefik-upst… │
traefik-upst… │ Initial Build
traefik-upst… │ Running cmd: helm repo add traefik-upstream https://helm.traefik.io/traefik --force-update
traefik-upst… │ "traefik-upstream" has been added to your repositories
      traefik │
      traefik │ Initial Build
      traefik │ STEP 1/1 — Deploying
      traefik │      Running cmd: python3 "/Users/.../Library/Application Support/tilt-dev/tilt_modules/github.com/tilt-dev/tilt-extensions/helm_resource/helm-apply-helper.py" --create-namespace
      traefik │      Running cmd: ['helm', 'upgrade', '--install', '--create-namespace', '--namespace', 'traefik', 'traefik', 'traefik-upstream/traefik']
      traefik │      Release "traefik" does not exist. Installing it now.
      traefik │      NAME: traefik
      traefik │      LAST DEPLOYED: Mon Jul  4 15:30:10 2022
      traefik │      NAMESPACE: traefik
      traefik │      STATUS: deployed
      traefik │      REVISION: 1
      traefik │      TEST SUITE: None
      traefik │      Running cmd: ['helm', 'get', 'manifest', '--namespace', 'traefik', 'traefik']
      traefik │      Running cmd: ['kubectl', 'get', '-oyaml', '-f', '-']
      traefik │      Error from server (NotFound): services "traefik" not found
      traefik │      Traceback (most recent call last):
      traefik │        File "/Users/.../Library/Application Support/tilt-dev/tilt_modules/github.com/tilt-dev/tilt-extensions/helm_resource/helm-apply-helper.py", line 105, in <module>
      traefik │          completed.check_returncode()
      traefik │        File "/Users/.../.asdf/installs/python/3.9.6/lib/python3.9/subprocess.py", line 460, in check_returncode
      traefik │          raise CalledProcessError(self.returncode, self.args, self.stdout,
      traefik │      subprocess.CalledProcessError: Command '['kubectl', 'get', '-oyaml', '-f', '-']' returned non-zero exit status 1.
      traefik │
      traefik │ ERROR: Build Failed: apply command exited with status 1
     ...
```

The `traefik` service is present and healthy but the `kubectl` command run by `helm_resource` has failed to find it:

```
❯ kubectl get pods --all-namespaces
NAMESPACE     NAME                                     READY   STATUS    RESTARTS         AGE
kube-system...
kube-system...
traefik       traefik-f89df87d4-zpj9d                  1/1     Running   0                2m45s
```

The patch in #413 works around this bug by forcing `kubectl` to search the correct namespace.

**Comment by nicks** [comment]
thanks for the repro case!

The problem is that traefik installs services embedded in a v1.List, rather than with plain YAML. i'm looking into fixing the helm namespace defaulter. 

This comment has more https://github.com/tilt-dev/tilt-extensions/issues/374#issuecomment-1089271912 on why using `kubectl` defaulting isn't what we want.

**Comment by nicks** [comment]
also filed this feature request - https://github.com/tilt-dev/tilt/issues/5884, which is related
