### ISSUE TITLE
helm-resource: different namespaces breaking on Windows

### ISSUE THREAD

**Issue by markmixson** [tilt-dev/tilt-extensions#435]
I'm installing an oracle db helm chart (https://github.com/oracle/docker-images/tree/main/OracleDatabase/SingleInstance/helm-charts/oracle-db) using helm_resource in a separate namespace called "oracle" using Minikube.  On Macs/Linux, this works fine.  But on Windows, the helm-apply-helper.py script gets confused.

```
     Running cmd: ['helm', 'get', 'manifest', '--namespace', 'oracle', 'db19c']
     Running cmd: ['kubectl', 'get', '-oyaml', '-f', '-']
     Error from server (NotFound): secrets "db19c-oracle-db" not found
     Error from server (NotFound): persistentvolumeclaims "db19c-oracle-db" not found
     Error from server (NotFound): services "db19c-oracle-db" not found
     Error from server (NotFound): deployments.apps "db19c-oracle-db" not found
     Traceback (most recent call last):
       File "C:\Users\ss4ro\AppData\Local\tilt-dev\tilt_modules\github.com\tilt-dev\tilt-extensions\helm_resource\helm-apply-helper.py", line 77, in <module>
         completed.check_returncode()
       File "C:\Users\ss4ro\AppData\Local\Programs\Python\Python38\lib\subprocess.py", line 444, in check_returncode
         raise CalledProcessError(self.returncode, self.args, self.stdout,
     subprocess.CalledProcessError: Command '['kubectl', 'get', '-oyaml', '-f', '-']' returned non-zero exit status 1.

Build Failed: apply command exited with status 1
```

When I change helm-apply-helper.py to include the namespace with kubectl_cmd, everything works fine:
```
if namespace:
  install_cmd.extend(['--namespace', namespace])
  get_cmd.extend(['--namespace', namespace])
  kubectl_cmd.extend(['--namespace', namespace])
```

I have not tried to figure out why this works on Mac/Linux but not Windows though. . .

**Comment by markmixson** [comment]
I tried to fix this trivially in #437 but appears that's wrong.  Also the tests for helm_resource do not pass in Windows.

helm 3.9.2
kubectl 1.24.3
minikube 1.26.1
kubernetes 1.24.3
tilt 0.30.6

```
++ dirname '.\test.sh'
+ cd .
+ tilt ci
Tilt started on http://localhost:10350/
v0.30.5, built 2022-07-14

Initial Build
Loading Tiltfile at: C:\Users\myuser\Documents\tilt-extensions\helm_resource\test\Tiltfile
Successfully loaded Tiltfile (4.9678ms)
     unittest │
     unittest │ Initial Build
     unittest │ Running cmd: python3 ../namespacing_test.py
     unittest │ ....
     unittest │ ----------------------------------------------------------------------
     unittest │ Ran 4 tests in 0.001s
     unittest │
     unittest │ OK
helm-repo-bi… │
helm-repo-bi… │ Initial Build
helm-repo-bi… │ Running cmd: helm repo add bitnami https://charts.bitnami.com/bitnami --force-update
   helloworld │
   helloworld │ Initial Build
   helloworld │ STEP 1/3 — Building Dockerfile: [helloworld-image]
   helloworld │ Building Dockerfile for platform linux/amd64:
   helloworld │   FROM busybox
   helloworld │   WORKDIR /app
   helloworld │   ADD . .
   helloworld │   ENTRYPOINT ./main.sh
   helloworld │
   helloworld │
   helloworld │      Building image
   helloworld │      [1/3] FROM docker.io/library/busybox@sha256:ef320ff10026a50cf5f0213d35537ce0041ac1d96e9b7800bafd8bc9eff6c693
   helloworld │      [background] read source files
   helloworld │      [background] read source files 433B [done: 27ms]
   helloworld │      [2/3] WORKDIR /app [cached]
   helloworld │      [3/3] ADD . . [cached]
   helloworld │      exporting to image
   helloworld │
   helloworld │ STEP 2/3 — Pushing helloworld-image:tilt-a8c987cb4cc21d34
   helloworld │      Skipping push: building on cluster's container runtime
   helloworld │
   helloworld │ STEP 3/3 — Deploying
   helloworld │      Running cmd: python3 C:\Users\myuser\Documents\tilt-extensions\helm_resource\helm-apply-helper.py --create-namespace
   helloworld │      Running cmd: ['helm', 'upgrade', '--install', '--create-namespace', '--set', 'image.repository=helloworld-image', '--set', 'image.tag=tilt-a8c987cb4cc21d34', '--namespace', 'app', 'helloworld', './helloworld']
helm-repo-bi… │ "bitnami" has been added to your repositories
   helloworld │      Release "helloworld" has been upgraded. Happy Helming!
   helloworld │      NAME: helloworld
   helloworld │      LAST DEPLOYED: Wed Aug 10 18:31:11 2022
   helloworld │      NAMESPACE: app
   helloworld │      STATUS: deployed
   helloworld │      REVISION: 2
   helloworld │      NOTES:
   helloworld │      1. Get the application URL by running these commands:
   helloworld │        export POD_NAME=$(kubectl get pods --namespace app -l "app.kubernetes.io/name=helloworld,app.kubernetes.io/instance=helloworld" -o jsonpath="{.items[0].metadata.name}")
   helloworld │        export CONTAINER_PORT=$(kubectl get pod --namespace app $POD_NAME -o jsonpath="{.spec.containers[0].ports[0].containerPort}")
   helloworld │        echo "Visit http://127.0.0.1:8080 to use your application"
   helloworld │        kubectl --namespace app port-forward $POD_NAME 8080:$CONTAINER_PORT
   helloworld │      Running cmd: ['helm', 'get', 'manifest', '--namespace', 'app', 'helloworld']
   helloworld │      Running cmd: ['kubectl', 'get', '-oyaml', '-f', '-']
   helloworld │      Error from server (NotFound): serviceaccounts "helloworld" not found
   helloworld │      Error from server (NotFound): configmaps "configmap-default-namespace" not found
   helloworld │      Error from server (NotFound): configmaps "configmap-empty-namespace" not found
   helloworld │      Error from server (NotFound): configmaps "configmap-namespace-data" not found
   helloworld │      Error from server (NotFound): services "helloworld" not found
   helloworld │      Error from server (NotFound): deployments.apps "helloworld" not found
    memcached │
    memcached │ Initial Build
    memcached │ STEP 1/1 — Deploying
    memcached │      Running cmd: python3 C:\Users\myuser\Documents\tilt-extensions\helm_resource\helm-apply-helper.py
   helloworld │      Traceback (most recent call last):
   helloworld │        File "C:\Users\myuser\Documents\tilt-extensions\helm_resource\helm-apply-helper.py", line 77, in <module>
   helloworld │          completed.check_returncode()
   helloworld │        File "C:\Python310\lib\subprocess.py", line 456, in check_returncode
   helloworld │          raise CalledProcessError(self.returncode, self.args, self.stdout,
   helloworld │      subprocess.CalledProcessError: Command '['kubectl', 'get', '-oyaml', '-f', '-']' returned non-zero exit status 1.
   helloworld │
   helloworld │ ERROR: Build Failed: apply command exited with status 1
   helloworld │ stdout:
   helloworld │ apiVersion: v1
   helloworld │ items:
   helloworld │ - apiVersion: v1
   helloworld │   data:
   helloworld │     hello: world
   helloworld │   kind: ConfigMap
   helloworld │   metadata:
   helloworld │     annotations:
   helloworld │       meta.helm.sh/release-name: helloworld
   helloworld │       meta.helm.sh/release-namespace: app
   helloworld │     creationTimestamp: "2022-08-10T22:29:47Z"
   helloworld │     lab
   helloworld │ ... [truncated by Tilt] ...
   helloworld │ l: TCP
   helloworld │       targetPort: http
   helloworld │     selector:
   helloworld │       app.kubernetes.io/instance: helloworld
   helloworld │       app.kubernetes.io/name: helloworld
   helloworld │     sessionAffinity: None
   helloworld │     type: ClusterIP
   helloworld │   status:
   helloworld │     loadBalancer: {}
   helloworld │ kind: List
   helloworld │ metadata:
   helloworld │   resourceVersion: ""
   helloworld │
helloregistry │
helloregistry │ Initial Build
helloregistry │ STEP 1/2 — Loading cached images
helloregistry │      - helloworld-image:tilt-a8c987cb4cc21d34
helloregistry │
helloregistry │ STEP 2/2 — Deploying
helloregistry │      Running cmd: python3 C:\Users\myuser\Documents\tilt-extensions\helm_resource\helm-apply-helper.py --create-namespace
Error: apply command exited with status 1
stdout:
apiVersion: v1
items:
- apiVersion: v1
  data:
    hello: world
  kind: ConfigMap
  metadata:
    annotations:
      meta.helm.sh/release-name: helloworld
      meta.helm.sh/release-namespace: app
    creationTimestamp: "2022-08-10T22:29:47Z"
    lab
... [truncated by Tilt] ...
l: TCP
      targetPort: http
    selector:
      app.kubernetes.io/instance: helloworld
      app.kubernetes.io/name: helloworld
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
```

**Comment by markmixson** [comment]
OK after looking at this. . .

1. Windows doesn't typically use `python3` as an executable. . . should be `py -3`
2. The default namespacing code uses kubectl output that doesn't consider Windows endline characters `\r\n`.  Replacing those with `\n` makes everything happy.
3. The tests are designed to run from unix shells and won't run in Windows.  Need to be platform agnostic (python-based at least).

**Comment by markmixson** [comment]
See #438 to resolve this
