### ISSUE TITLE
`helm_resource` KeyError

### ISSUE THREAD

**Issue by StephanMeijer** [tilt-dev/tilt-extensions#528]
```
     Running cmd: python3 /home/steve/.local/share/tilt-dev/tilt_modules/github.com/tilt-dev/tilt-extensions/helm_resource/helm-apply-helper.py
     Traceback (most recent call last):
       File "/home/steve/.local/share/tilt-dev/tilt_modules/github.com/tilt-dev/tilt-extensions/helm_resource/helm-apply-helper.py", line 24, in <module>
         image = os.environ['TILT_IMAGE_%s' % i]
                 ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^
       File "<frozen os>", line 679, in __getitem__
     KeyError: 'TILT_IMAGE_3'
```

Probably caused due to using multiple same Docker refs:

```py
load('ext://helm_resource', 'helm_resource', 'helm_repo')

docker_build('dev-dcs-php-generic',
             '.',
             pull=True,
             dockerfile='.ci/docker/php-generic/Dockerfile')

docker_build('dev-dcs-php-pandoc',
             '.',
             dockerfile='.ci/docker/php-libreoffice/Dockerfile',
             build_args={'BASE_IMAGE': 'dev-dcs-php-generic'})

docker_build('dev-dcs-php-libreoffice',
             '.',
             dockerfile='.ci/docker/php-libreoffice/Dockerfile',
             build_args={'BASE_IMAGE': 'dev-dcs-php-generic'})

helm_repo('nldoc', 'https://gitlab.com/api/v4/projects/50351992/packages/helm/stable')
helm_resource(
    name='dev-dcs',
    chart='nldoc/nldoc-stack',
    image_deps=[
        'dev-dcs-php-generic',
        'dev-dcs-php-generic',
        'dev-dcs-php-generic',
        'dev-dcs-php-pandoc',
        'dev-dcs-php-libreoffice',
    ],
    image_keys=[
        ("nldoc-conversion.php-dcs-inbound.image.repository",
         "nldoc-conversion.php-dcs-inbound.image.tag"),
        ("nldoc-conversion.php-dcs-publicatietool-inbound.image.repository",
         "nldoc-conversion.php-dcs-publicatietool-inbound.image.tag"),
        ("nldoc-conversion.php-dcs-outbound.image.repository=dev-dcs-php-generic",
         "nldoc-conversion.php-dcs-outbound.image.tag"),
        ("nldoc-conversion.php-dcs-pandoc.image.repository",
         "nldoc-conversion.php-dcs-pandoc.image.tag"),
        ("nldoc-conversion.php-dcs-libreoffice.image.repository",
         "nldoc-conversion.php-dcs-libreoffice.image.tag")
    ]
)
```

**Comment by StephanMeijer** [comment]
Only occurs when trying to reuse an image

**Comment by cr1st1p** [comment]
having the same issue. Reusing the same container image in several places.
